name: Manual Release

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Using Flutter version 3.22.2

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TechieAi-android
        path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Using Flutter version 3.22.2

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows app
      run: flutter build windows

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TechieAi-windows
        path: build/windows/x64/Release/techie_ai.exe # Specify x64 architecture explicitly

  build-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Using Flutter version 3.22.2

    - name: Install dependencies
      run: flutter pub get

    - name: Build web app
      run: flutter build web --release

    - name: Upload Web Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TechieAi-web
        path: build/web/

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-windows, build-web]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.0-alpha # Adjust the version/tag as needed
        release_name: TechieAi # Release name
        draft: false
        prerelease: false

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: TechieAi-android.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Windows App to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/windows/x64/Release/techie_ai.exe # Specify x64 architecture explicitly
        asset_name: TechieAi-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload Web App to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/web/ # Adjust the path if necessary
        asset_name: TechieAi-web.zip # You might want to zip the web build
        asset_content_type: application/zip
