name: Manual Release

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Using Flutter version 3.22.2

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TechieAi-android
        path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Using Flutter version 3.22.2

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows app
      run: flutter build windows --release

    - name: Archive Windows Build
      run: |
        cd build/windows/runner/Release
        zip -r TechieAi-windows.zip .

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TechieAi-windows
        path: build/windows/runner/Release/TechieAi-windows.zip

  build-ios:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Using Flutter version 3.22.2

    - name: Install dependencies
      run: flutter pub get

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Build iOS app
      run: flutter build ios --release --no-codesign

    - name: Archive iOS Build
      run: |
        cd build/ios/iphoneos
        zip -r TechieAi-ios.zip Runner.app

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TechieAi-ios
        path: build/ios/iphoneos/TechieAi-ios.zip

  build-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Using Flutter version 3.22.2

    - name: Install dependencies
      run: flutter pub get

    - name: Build web app
      run: flutter build web --release

    - name: Archive Web Build
      run: |
        cd build/web
        zip -r TechieAi-web.zip .

    - name: Upload Web Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TechieAi-web
        path: build/web/TechieAi-web.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-windows, build-ios, build-web]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0 # Adjust the version/tag as needed
        release_name: TechieAi # Release name
        draft: false
        prerelease: false

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: TechieAi-android.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Windows App to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/windows/runner/Release/TechieAi-windows.zip
        asset_name: TechieAi-windows.zip
        asset_content_type: application/zip

    - name: Upload iOS App to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/ios/iphoneos/TechieAi-ios.zip
        asset_name: TechieAi-ios.zip
        asset_content_type: application/zip

    - name: Upload Web App to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/web/TechieAi-web.zip
        asset_name: TechieAi-web.zip
        asset_content_type: application/zip
